server:
  servlet:
    context-path: /elleshop

mybatis:
  type-aliases-package: com.mars.elleshop.entity
  mapper-locations: classpath:mapper/*.xml
  #下划线转驼峰
  configuration:
   map-underscore-to-camel-case: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.13.115.175/elleshop?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 5
  thymeleaf:
    cache: false

logging:
  level:
    org:
      thymeleaf: info






